### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by Milky123123** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#24] opened 2021-06-28 02:42 UTC
Hi,

I was trying to use the SFEMPsheild  to make and mp3 player with a LCD screen and buttons.
I'm working on a new version of this.....
https://www.tindie.com/products/krystalstate/mp3wav-player-stomp-box-stage-bro-2000/

Anyways, I am pulling the Title and Artist name using the code excerpt below and I find that sometimes it pulls the Title and Artist characters correctly.....but sometimes it displays just a bunch of nonsense characters.  Any idea on what I am doing wrong? I am kind of stuck.

//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
         char title[30]; // buffer to contain the extract the Title from the current filehandles
         char artist[30]; // buffer to contain the extract the artist name from the current filehandles
   
           MP3player.trackTitle((char*)&title);
           MP3player.trackArtist((char*)&artist);
           
           lcd.write((byte*)&title, 30);
           lcd.setCursor(0,1);
           lcd.print("by:  ");
           lcd.write((byte*)&artist, 30);
//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Thanks,

Mike.

**Comment by mpflaga** [comment] 2021-06-28 16:16
Can you please describe if the unexpected behaviour occurs repeatedly with the same same audio file? or if it randomly occurs on any file? Does it sometimes work and sometimes not?

It has been a while since I last worked on that project. Where I recall this section of code very much is dependant on the format of the file. And some of these formats are not fixed in stone. It may be possible that a particular files underlying format is not known by this library. 
I recall advising some users of this library that they needed to re-compile the audio file, with a tool like Audacity. It would read the file and headers, then could save them back. The audio would remain unchained but the headers and such would be cleaned up. 

Whereas if it randomly works on the same file, but sometimes not. Then it is will be more difficult to find the issue. 
If this is the case, then I would brake the code up in to pieces. starting with the original demos provided. and confirming that they work repeatedly as expected. then adding pieces back in. It could be running out of RAM. I don't know at this point. 

I hope this helps.

**Comment by Milky123123** [comment] 2021-06-28 16:41
Morning,
Its the same file having the same error every time. and the ones that work, work every time.

Thanks, I will use your suggestion and try to use audacity to recompile the audio file.

Thanks,

Mike.

**Comment by mpflaga** [comment] 2021-08-10 17:52
I assume this fixed the issue and will close the issue.

**Closed by mpflaga** 2021-08-10 17:52 UTC
